import type { FormatConfig } from './types';

export const FORMAT_CONFIGS: Record<string, FormatConfig> = {
  'standard-5x5': {
    slug: 'standard-5x5',
    name: 'Standard 5×5 Risk Matrix',
    description: 'Classic 5×5 likelihood and severity risk assessment matrix',
    scoringType: 'matrix-5x5',
    isFree: true,
    riskScale: '5x5',
    headerColor: '1B5B50',
    accentColor: 'D4A44C',
    hasRiskMatrix: true,
    hasResidualRisk: true,
    hasMethodStatement: true,
    hasEnvironmental: false,
    hasFirePermit: false,
    hasClientBranding: false,
    hasDemolition: false,
    sections: [
      {
        id: 'header',
        title: 'Document Header',
        type: 'header',
        required: true,
      },
      {
        id: 'info-table',
        title: 'Project Information',
        type: 'info-table',
        required: true,
      },
      {
        id: 'risk-matrix-visual',
        title: '5×5 Risk Matrix',
        type: 'risk-matrix',
        required: true,
      },
      {
        id: 'risk-assessment',
        title: 'Risk Assessment',
        type: 'risk-assessment',
        required: true,
      },
      {
        id: 'method-statement',
        title: 'Method Statement',
        type: 'method-statement',
        required: true,
      },
      {
        id: 'ppe',
        title: 'Personal Protective Equipment',
        type: 'ppe',
        required: true,
      },
      {
        id: 'emergency',
        title: 'Emergency Procedures',
        type: 'emergency',
        required: true,
      },
      {
        id: 'signatures',
        title: 'Approvals & Signatures',
        type: 'signatures',
        required: true,
      },
    ],
  },

  'hml-simple': {
    slug: 'hml-simple',
    name: 'H/M/L Simple Assessment',
    description: 'Quick 3×3 High/Medium/Low risk assessment',
    scoringType: 'hml',
    isFree: true,
    riskScale: '3x3',
    headerColor: '1B5B50',
    accentColor: 'D4A44C',
    hasRiskMatrix: true,
    hasResidualRisk: false,
    hasMethodStatement: true,
    hasEnvironmental: false,
    hasFirePermit: false,
    hasClientBranding: false,
    hasDemolition: false,
    sections: [
      {
        id: 'header',
        title: 'Document Header',
        type: 'header',
        required: true,
      },
      {
        id: 'info-table',
        title: 'Project Information',
        type: 'info-table',
        required: true,
      },
      {
        id: 'risk-matrix-visual',
        title: 'H/M/L Risk Matrix',
        type: 'risk-matrix',
        required: true,
      },
      {
        id: 'risk-assessment',
        title: 'Risk Assessment',
        type: 'risk-assessment',
        required: true,
      },
      {
        id: 'ppe',
        title: 'Personal Protective Equipment',
        type: 'ppe',
        required: true,
      },
      {
        id: 'signatures',
        title: 'Approvals & Signatures',
        type: 'signatures',
        required: true,
      },
    ],
  },

  'tier-1-formal': {
    slug: 'tier-1-formal',
    name: 'Tier 1 Formal Assessment',
    description: 'Large contractor formal RAMS format with tiered approach',
    scoringType: 'tiered',
    isFree: false,
    riskScale: '5x5',
    headerColor: '1B5B50',
    accentColor: 'D4A44C',
    hasRiskMatrix: true,
    hasResidualRisk: true,
    hasMethodStatement: true,
    hasEnvironmental: false,
    hasFirePermit: false,
    hasClientBranding: false,
    hasDemolition: false,
    sections: [
      {
        id: 'header',
        title: 'Document Header',
        type: 'header',
        required: true,
      },
      {
        id: 'document-control',
        title: 'Document Control',
        type: 'info-table',
        required: true,
      },
      {
        id: 'scope-of-work',
        title: 'Scope of Work',
        type: 'info-table',
        required: true,
      },
      {
        id: 'risk-matrix-visual',
        title: 'Risk Acceptability Matrix',
        type: 'risk-matrix',
        required: true,
      },
      {
        id: 'risk-assessment',
        title: 'Comprehensive Risk Assessment',
        type: 'risk-assessment',
        required: true,
      },
      {
        id: 'method-statement',
        title: 'Detailed Method Statement',
        type: 'method-statement',
        required: true,
      },
      {
        id: 'ppe',
        title: 'Personal Protective Equipment Requirements',
        type: 'ppe',
        required: true,
      },
      {
        id: 'emergency',
        title: 'Emergency Response Procedures',
        type: 'emergency',
        required: true,
      },
      {
        id: 'competency',
        title: 'Competency & Training Requirements',
        type: 'checklist',
        required: true,
      },
      {
        id: 'signatures',
        title: 'Document Approval & Sign-Off',
        type: 'signatures',
        required: true,
      },
    ],
  },

  'small-works-quick': {
    slug: 'small-works-quick',
    name: 'Small Works Quick Assessment',
    description: 'Streamlined format for small-scale tasks and maintenance work',
    scoringType: 'hml',
    isFree: true,
    riskScale: '3x3',
    headerColor: '1B5B50',
    accentColor: 'D4A44C',
    hasRiskMatrix: false,
    hasResidualRisk: false,
    hasMethodStatement: true,
    hasEnvironmental: false,
    hasFirePermit: false,
    hasClientBranding: false,
    hasDemolition: false,
    sections: [
      {
        id: 'header',
        title: 'Document Header',
        type: 'header',
        required: true,
      },
      {
        id: 'info-table',
        title: 'Work Details',
        type: 'info-table',
        required: true,
      },
      {
        id: 'risk-assessment',
        title: 'Risk & Control Assessment',
        type: 'risk-assessment',
        required: true,
      },
      {
        id: 'ppe',
        title: 'PPE & Safety Equipment',
        type: 'ppe',
        required: true,
      },
      {
        id: 'signatures',
        title: 'Sign-Off',
        type: 'signatures',
        required: true,
      },
    ],
  },

  'cdm-principal': {
    slug: 'cdm-principal',
    name: 'CDM Principal Contractor',
    description: 'CDM 2015 regulations compliant principal contractor format',
    scoringType: 'cdm',
    isFree: false,
    riskScale: '5x5',
    headerColor: '1B5B50',
    accentColor: 'D4A44C',
    hasRiskMatrix: true,
    hasResidualRisk: true,
    hasMethodStatement: true,
    hasEnvironmental: false,
    hasFirePermit: false,
    hasClientBranding: false,
    hasDemolition: false,
    sections: [
      {
        id: 'header',
        title: 'CDM Notification',
        type: 'header',
        required: true,
      },
      {
        id: 'info-table',
        title: 'Project Details & CDM Information',
        type: 'info-table',
        required: true,
      },
      {
        id: 'risk-matrix-visual',
        title: 'Risk Assessment Matrix',
        type: 'risk-matrix',
        required: true,
      },
      {
        id: 'risk-assessment',
        title: 'Significant Risk Identification',
        type: 'risk-assessment',
        required: true,
      },
      {
        id: 'method-statement',
        title: 'Construction Method Statement',
        type: 'method-statement',
        required: true,
      },
      {
        id: 'ppe',
        title: 'Personal Protective Equipment',
        type: 'ppe',
        required: true,
      },
      {
        id: 'emergency',
        title: 'Emergency & First Aid Arrangements',
        type: 'emergency',
        required: true,
      },
      {
        id: 'welfare',
        title: 'Welfare Facilities',
        type: 'checklist',
        required: true,
      },
      {
        id: 'signatures',
        title: 'CDM Approvals',
        type: 'signatures',
        required: true,
      },
    ],
  },

  'maintenance-ops': {
    slug: 'maintenance-ops',
    name: 'Maintenance Operations',
    description: 'Format for ongoing maintenance and operational activities',
    scoringType: 'hml',
    isFree: false,
    riskScale: '3x3',
    headerColor: '1B5B50',
    accentColor: 'D4A44C',
    hasRiskMatrix: true,
    hasResidualRisk: false,
    hasMethodStatement: true,
    hasEnvironmental: false,
    hasFirePermit: false,
    hasClientBranding: false,
    hasDemolition: false,
    sections: [
      {
        id: 'header',
        title: 'Maintenance Activity Notice',
        type: 'header',
        required: true,
      },
      {
        id: 'info-table',
        title: 'Activity Information',
        type: 'info-table',
        required: true,
      },
      {
        id: 'risk-matrix-visual',
        title: 'Risk Matrix',
        type: 'risk-matrix',
        required: true,
      },
      {
        id: 'risk-assessment',
        title: 'Hazard & Risk Assessment',
        type: 'risk-assessment',
        required: true,
      },
      {
        id: 'method-statement',
        title: 'Maintenance Procedure',
        type: 'method-statement',
        required: true,
      },
      {
        id: 'ppe',
        title: 'Personal Protective Equipment',
        type: 'ppe',
        required: true,
      },
      {
        id: 'emergency',
        title: 'Emergency Response',
        type: 'emergency',
        required: true,
      },
      {
        id: 'signatures',
        title: 'Approval & Authorisation',
        type: 'signatures',
        required: true,
      },
    ],
  },

  'client-branded': {
    slug: 'client-branded',
    name: 'Client Branded Assessment',
    description: 'White-label format with client company branding and logo',
    scoringType: 'matrix-5x5',
    isFree: false,
    riskScale: '5x5',
    headerColor: '1B5B50',
    accentColor: 'D4A44C',
    hasRiskMatrix: true,
    hasResidualRisk: true,
    hasMethodStatement: true,
    hasEnvironmental: false,
    hasFirePermit: false,
    hasClientBranding: true,
    hasDemolition: false,
    sections: [
      {
        id: 'header',
        title: 'Branded Document Header',
        type: 'header',
        required: true,
      },
      {
        id: 'info-table',
        title: 'Project Information',
        type: 'info-table',
        required: true,
      },
      {
        id: 'risk-matrix-visual',
        title: 'Risk Matrix',
        type: 'risk-matrix',
        required: true,
      },
      {
        id: 'risk-assessment',
        title: 'Risk Assessment',
        type: 'risk-assessment',
        required: true,
      },
      {
        id: 'method-statement',
        title: 'Method Statement',
        type: 'method-statement',
        required: true,
      },
      {
        id: 'ppe',
        title: 'Personal Protective Equipment',
        type: 'ppe',
        required: true,
      },
      {
        id: 'emergency',
        title: 'Emergency Procedures',
        type: 'emergency',
        required: true,
      },
      {
        id: 'signatures',
        title: 'Approvals',
        type: 'signatures',
        required: true,
      },
    ],
  },

  'environmental-plus': {
    slug: 'environmental-plus',
    name: 'Environmental Plus Assessment',
    description: 'Extended format including environmental risk and impact assessment',
    scoringType: 'matrix-5x5',
    isFree: false,
    riskScale: '5x5',
    headerColor: '1B5B50',
    accentColor: 'D4A44C',
    hasRiskMatrix: true,
    hasResidualRisk: true,
    hasMethodStatement: true,
    hasEnvironmental: true,
    hasFirePermit: false,
    hasClientBranding: false,
    hasDemolition: false,
    sections: [
      {
        id: 'header',
        title: 'Document Header',
        type: 'header',
        required: true,
      },
      {
        id: 'info-table',
        title: 'Project Information',
        type: 'info-table',
        required: true,
      },
      {
        id: 'risk-matrix-visual',
        title: 'Safety Risk Matrix',
        type: 'risk-matrix',
        required: true,
      },
      {
        id: 'risk-assessment',
        title: 'Safety Risk Assessment',
        type: 'risk-assessment',
        required: true,
      },
      {
        id: 'environmental',
        title: 'Environmental Impact Assessment',
        type: 'environmental',
        required: true,
      },
      {
        id: 'method-statement',
        title: 'Method Statement',
        type: 'method-statement',
        required: true,
      },
      {
        id: 'ppe',
        title: 'Personal Protective Equipment',
        type: 'ppe',
        required: true,
      },
      {
        id: 'emergency',
        title: 'Emergency & Environmental Procedures',
        type: 'emergency',
        required: true,
      },
      {
        id: 'signatures',
        title: 'Approvals',
        type: 'signatures',
        required: true,
      },
    ],
  },

  'fire-hot-works': {
    slug: 'fire-hot-works',
    name: 'Fire & Hot Works Permit',
    description: 'Specialised format for fire-related and hot works activities',
    scoringType: 'matrix-5x5',
    isFree: false,
    riskScale: '5x5',
    headerColor: 'C93C3C',
    accentColor: 'F5A623',
    hasRiskMatrix: true,
    hasResidualRisk: true,
    hasMethodStatement: true,
    hasEnvironmental: false,
    hasFirePermit: true,
    hasClientBranding: false,
    hasDemolition: false,
    sections: [
      {
        id: 'header',
        title: 'Hot Works Permit Header',
        type: 'header',
        required: true,
      },
      {
        id: 'fire-permit',
        title: 'Hot Works Permit Details',
        type: 'fire-permit',
        required: true,
      },
      {
        id: 'info-table',
        title: 'Activity Information',
        type: 'info-table',
        required: true,
      },
      {
        id: 'risk-matrix-visual',
        title: 'Fire Risk Matrix',
        type: 'risk-matrix',
        required: true,
      },
      {
        id: 'risk-assessment',
        title: 'Fire & Hot Works Risk Assessment',
        type: 'risk-assessment',
        required: true,
      },
      {
        id: 'method-statement',
        title: 'Hot Works Method Statement',
        type: 'method-statement',
        required: true,
      },
      {
        id: 'ppe',
        title: 'Personal Protective Equipment',
        type: 'ppe',
        required: true,
      },
      {
        id: 'emergency',
        title: 'Fire & Emergency Procedures',
        type: 'emergency',
        required: true,
      },
      {
        id: 'signatures',
        title: 'Permit Approvals',
        type: 'signatures',
        required: true,
      },
    ],
  },

  'demolition-advanced': {
    slug: 'demolition-advanced',
    name: 'Demolition Advanced Assessment',
    description: 'Comprehensive format for complex demolition projects',
    scoringType: 'matrix-5x5',
    isFree: false,
    riskScale: '5x5',
    headerColor: '1B5B50',
    accentColor: 'D4A44C',
    hasRiskMatrix: true,
    hasResidualRisk: true,
    hasMethodStatement: true,
    hasEnvironmental: true,
    hasFirePermit: false,
    hasClientBranding: false,
    hasDemolition: true,
    sections: [
      {
        id: 'header',
        title: 'Demolition RAMS Header',
        type: 'header',
        required: true,
      },
      {
        id: 'info-table',
        title: 'Demolition Project Information',
        type: 'info-table',
        required: true,
      },
      {
        id: 'demolition-scope',
        title: 'Scope of Demolition Works',
        type: 'notes',
        required: true,
      },
      {
        id: 'risk-matrix-visual',
        title: 'Risk Assessment Matrix',
        type: 'risk-matrix',
        required: true,
      },
      {
        id: 'risk-assessment',
        title: 'Comprehensive Risk Assessment',
        type: 'risk-assessment',
        required: true,
      },
      {
        id: 'environmental',
        title: 'Environmental & Contamination Assessment',
        type: 'environmental',
        required: true,
      },
      {
        id: 'method-statement',
        title: 'Demolition Method Statement',
        type: 'method-statement',
        required: true,
      },
      {
        id: 'ppe',
        title: 'Personal Protective Equipment & Safety Equipment',
        type: 'ppe',
        required: true,
      },
      {
        id: 'emergency',
        title: 'Emergency & Environmental Procedures',
        type: 'emergency',
        required: true,
      },
      {
        id: 'signatures',
        title: 'Approvals & Authorisations',
        type: 'signatures',
        required: true,
      },
    ],
  },
};

export function getFormatConfig(slug: string): FormatConfig | null {
  return FORMAT_CONFIGS[slug] || null;
}

export function getAllFormats(): FormatConfig[] {
  return Object.values(FORMAT_CONFIGS);
}

export function getFreeFormats(): FormatConfig[] {
  return Object.values(FORMAT_CONFIGS).filter((config) => config.isFree);
}

export function getPaidFormats(): FormatConfig[] {
  return Object.values(FORMAT_CONFIGS).filter((config) => !config.isFree);
}
