// src/lib/sign-maker-data.ts
// Complete ISO 7010 sign database – 300 icons

export type SignCategory = "prohibition" | "warning" | "mandatory" | "safe" | "fire";

export interface SignIcon {
  code: string;
  label: string;
  category: SignCategory;
  /** Construction-site relevance: 1 = core, 2 = common, 3 = niche */
  relevance: 1 | 2 | 3;
}

export interface CategoryMeta {
  id: SignCategory;
  label: string;
  desc: string;
  /** ISO 3864 colour */
  bg: string;
  border: string;
  shape: "circle-bar" | "triangle" | "circle" | "rectangle";
}

export const CATEGORIES: CategoryMeta[] = [
  { id: "prohibition", label: "Prohibition", desc: "Actions you must NOT do", bg: "#A1262D", border: "#A1262D", shape: "circle-bar" },
  { id: "warning", label: "Warning", desc: "Hazards and dangers", bg: "#F5CA2B", border: "#21251E", shape: "triangle" },
  { id: "mandatory", label: "Mandatory", desc: "Actions you MUST do", bg: "#004873", border: "#FFFFFF", shape: "circle" },
  { id: "safe", label: "Safe Condition", desc: "Emergency & safety info", bg: "#008E5E", border: "#FFFFFF", shape: "rectangle" },
  { id: "fire", label: "Fire Equipment", desc: "Fire safety equipment", bg: "#A1262D", border: "#FFFFFF", shape: "rectangle" },
];

export const ICONS: SignIcon[] = [
  // ── PROHIBITION (P) ──
  { code: "p001", label: "General prohibition", category: "prohibition", relevance: 1 },
  { code: "p002", label: "No smoking", category: "prohibition", relevance: 1 },
  { code: "p003", label: "No open flame", category: "prohibition", relevance: 1 },
  { code: "p004", label: "No thoroughfare", category: "prohibition", relevance: 1 },
  { code: "p005", label: "Not drinking water", category: "prohibition", relevance: 2 },
  { code: "p006", label: "No forklift trucks / industrial vehicles", category: "prohibition", relevance: 1 },
  { code: "p007", label: "No access – active implanted cardiac devices", category: "prohibition", relevance: 3 },
  { code: "p008", label: "No metallic articles or watches", category: "prohibition", relevance: 3 },
  { code: "p009", label: "No climbing", category: "prohibition", relevance: 1 },
  { code: "p010", label: "Do not touch", category: "prohibition", relevance: 1 },
  { code: "p011", label: "Do not extinguish with water", category: "prohibition", relevance: 2 },
  { code: "p012", label: "No heavy load", category: "prohibition", relevance: 2 },
  { code: "p013", label: "No activated mobile phones", category: "prohibition", relevance: 2 },
  { code: "p014", label: "No access – metallic implants", category: "prohibition", relevance: 3 },
  { code: "p015", label: "No reaching in", category: "prohibition", relevance: 2 },
  { code: "p016", label: "Do not spray with water", category: "prohibition", relevance: 3 },
  { code: "p017", label: "No pushing", category: "prohibition", relevance: 3 },
  { code: "p018", label: "No sitting", category: "prohibition", relevance: 3 },
  { code: "p019", label: "No stepping on surface", category: "prohibition", relevance: 2 },
  { code: "p020", label: "Do not use lift in event of fire", category: "prohibition", relevance: 2 },
  { code: "p021", label: "No dogs", category: "prohibition", relevance: 2 },
  { code: "p022", label: "No eating or drinking", category: "prohibition", relevance: 1 },
  { code: "p023", label: "Do not obstruct", category: "prohibition", relevance: 2 },
  { code: "p024", label: "Do not walk or stand here", category: "prohibition", relevance: 1 },
  { code: "p025", label: "Do not use incomplete scaffold", category: "prohibition", relevance: 1 },
  { code: "p026", label: "Do not use device in water", category: "prohibition", relevance: 3 },
  { code: "p027", label: "Do not use lift for people", category: "prohibition", relevance: 2 },
  { code: "p028", label: "Do not wear gloves", category: "prohibition", relevance: 2 },
  { code: "p029", label: "No photography", category: "prohibition", relevance: 2 },
  { code: "p030", label: "Do not tie knots in rope", category: "prohibition", relevance: 3 },
  { code: "p031", label: "Do not alter switch state", category: "prohibition", relevance: 2 },
  { code: "p032", label: "Do not use for face grinding", category: "prohibition", relevance: 3 },
  { code: "p033", label: "Do not use for wet grinding", category: "prohibition", relevance: 3 },
  { code: "p034", label: "Do not use with hand-held grinder", category: "prohibition", relevance: 3 },
  { code: "p035", label: "No metal-studded footwear", category: "prohibition", relevance: 3 },
  { code: "p036", label: "No children allowed", category: "prohibition", relevance: 2 },
  { code: "p037", label: "Do not leave tow-track", category: "prohibition", relevance: 3 },
  { code: "p038", label: "Do not swing chair", category: "prohibition", relevance: 3 },
  { code: "p039", label: "Hot works prohibited", category: "prohibition", relevance: 1 },
  { code: "p040", label: "Do not set off fireworks", category: "prohibition", relevance: 3 },
  { code: "p041", label: "No leaning against", category: "prohibition", relevance: 2 },
  { code: "p042", label: "Not for pregnant women", category: "prohibition", relevance: 3 },
  { code: "p043", label: "Not for people under intoxication", category: "prohibition", relevance: 3 },
  { code: "p044", label: "No smart glasses", category: "prohibition", relevance: 3 },
  { code: "p045", label: "No campfire", category: "prohibition", relevance: 3 },
  { code: "p046", label: "Do not stretch out of toboggan", category: "prohibition", relevance: 3 },
  { code: "p047", label: "Do not ram toboggans", category: "prohibition", relevance: 3 },
  { code: "p048", label: "No running", category: "prohibition", relevance: 2 },
  { code: "p049", label: "No swimming", category: "prohibition", relevance: 3 },
  { code: "p050", label: "No snorkelling", category: "prohibition", relevance: 3 },
  { code: "p051", label: "No sub-aqua diving", category: "prohibition", relevance: 3 },
  { code: "p052", label: "No diving", category: "prohibition", relevance: 3 },
  { code: "p053", label: "No sailing", category: "prohibition", relevance: 3 },
  { code: "p054", label: "No windsurfing", category: "prohibition", relevance: 3 },
  { code: "p055", label: "No manually powered craft", category: "prohibition", relevance: 3 },
  { code: "p056", label: "No mechanically powered craft", category: "prohibition", relevance: 3 },
  { code: "p057", label: "No personal water craft", category: "prohibition", relevance: 3 },
  { code: "p058", label: "No towed water activity", category: "prohibition", relevance: 3 },
  { code: "p059", label: "No surf craft", category: "prohibition", relevance: 3 },
  { code: "p060", label: "No outdoor footwear", category: "prohibition", relevance: 3 },
  { code: "p061", label: "No jumping into water", category: "prohibition", relevance: 3 },
  { code: "p062", label: "No pushing into water", category: "prohibition", relevance: 3 },
  { code: "p063", label: "No body boarding", category: "prohibition", relevance: 3 },
  { code: "p064", label: "No surfing between flags", category: "prohibition", relevance: 3 },
  { code: "p065", label: "No kite surfing", category: "prohibition", relevance: 3 },
  { code: "p066", label: "No parasailing", category: "prohibition", relevance: 3 },
  { code: "p067", label: "No sand yachting", category: "prohibition", relevance: 3 },
  { code: "p068", label: "Do not expose to sunlight / hot surface", category: "prohibition", relevance: 3 },
  { code: "p069", label: "Not to be serviced by users", category: "prohibition", relevance: 3 },
  { code: "p070", label: "Do not put finger in hydromassage nozzle", category: "prohibition", relevance: 3 },
  { code: "p071", label: "Do not cross barrier", category: "prohibition", relevance: 2 },
  { code: "p072", label: "No jumping down", category: "prohibition", relevance: 2 },
  { code: "p073", label: "Do not close lid with burners operating", category: "prohibition", relevance: 3 },
  { code: "p074", label: "Child seat installation prohibited", category: "prohibition", relevance: 3 },

  // ── WARNING (W) ──
  { code: "w001", label: "General warning", category: "warning", relevance: 1 },
  { code: "w002", label: "Explosive material", category: "warning", relevance: 2 },
  { code: "w003", label: "Radioactive material / ionising radiation", category: "warning", relevance: 3 },
  { code: "w004", label: "Laser beam", category: "warning", relevance: 3 },
  { code: "w005", label: "Non-ionising radiation", category: "warning", relevance: 3 },
  { code: "w006", label: "Magnetic field", category: "warning", relevance: 3 },
  { code: "w007", label: "Floor-level obstacle", category: "warning", relevance: 1 },
  { code: "w008", label: "Drop / fall", category: "warning", relevance: 1 },
  { code: "w009", label: "Biological hazard", category: "warning", relevance: 2 },
  { code: "w010", label: "Low temperature / freezing", category: "warning", relevance: 2 },
  { code: "w011", label: "Slippery surface", category: "warning", relevance: 1 },
  { code: "w012", label: "Electricity", category: "warning", relevance: 1 },
  { code: "w013", label: "Guard dog", category: "warning", relevance: 2 },
  { code: "w014", label: "Forklift trucks / industrial vehicles", category: "warning", relevance: 1 },
  { code: "w015", label: "Overhead load", category: "warning", relevance: 1 },
  { code: "w016", label: "Toxic material", category: "warning", relevance: 1 },
  { code: "w017", label: "Hot surface", category: "warning", relevance: 1 },
  { code: "w018", label: "Automatic start-up", category: "warning", relevance: 2 },
  { code: "w019", label: "Crushing", category: "warning", relevance: 1 },
  { code: "w020", label: "Overhead obstacle", category: "warning", relevance: 1 },
  { code: "w021", label: "Flammable material", category: "warning", relevance: 1 },
  { code: "w022", label: "Sharp element", category: "warning", relevance: 2 },
  { code: "w023", label: "Corrosive substance", category: "warning", relevance: 1 },
  { code: "w024", label: "Crushing of hands", category: "warning", relevance: 2 },
  { code: "w025", label: "Counterrotating rollers", category: "warning", relevance: 3 },
  { code: "w026", label: "Battery charging", category: "warning", relevance: 2 },
  { code: "w027", label: "Optical radiation", category: "warning", relevance: 3 },
  { code: "w028", label: "Oxidising substance", category: "warning", relevance: 2 },
  { code: "w029", label: "Pressurised cylinder", category: "warning", relevance: 2 },
  { code: "w030", label: "Hand crushing – press brake tool", category: "warning", relevance: 3 },
  { code: "w031", label: "Hand crushing – press brake & material", category: "warning", relevance: 3 },
  { code: "w032", label: "Rapid workpiece movement – press brake", category: "warning", relevance: 3 },
  { code: "w033", label: "Barbed wire", category: "warning", relevance: 2 },
  { code: "w034", label: "Bull", category: "warning", relevance: 3 },
  { code: "w035", label: "Falling objects", category: "warning", relevance: 1 },
  { code: "w036", label: "Fragile roof", category: "warning", relevance: 1 },
  { code: "w037", label: "Remote operator controlled machine", category: "warning", relevance: 2 },
  { code: "w038", label: "Sudden loud noise", category: "warning", relevance: 2 },
  { code: "w039", label: "Falling ice", category: "warning", relevance: 2 },
  { code: "w040", label: "Roof avalanche", category: "warning", relevance: 3 },
  { code: "w041", label: "Asphyxiating atmosphere", category: "warning", relevance: 1 },
  { code: "w042", label: "Arc flash", category: "warning", relevance: 2 },
  { code: "w043", label: "Thin ice", category: "warning", relevance: 3 },
  { code: "w044", label: "Slipway", category: "warning", relevance: 3 },
  { code: "w045", label: "Towed water activity area", category: "warning", relevance: 3 },
  { code: "w046", label: "Surf craft area", category: "warning", relevance: 3 },
  { code: "w047", label: "Deep water", category: "warning", relevance: 2 },
  { code: "w048", label: "Shallow water (diving)", category: "warning", relevance: 3 },
  { code: "w049", label: "Submerged objects", category: "warning", relevance: 3 },
  { code: "w050", label: "Sudden drop in pool", category: "warning", relevance: 3 },
  { code: "w051", label: "Unprotected edge", category: "warning", relevance: 1 },
  { code: "w052", label: "Unstable cliff edge", category: "warning", relevance: 3 },
  { code: "w053", label: "Unstable cliff", category: "warning", relevance: 3 },
  { code: "w054", label: "Shark", category: "warning", relevance: 3 },
  { code: "w055", label: "Sewage effluent outfall", category: "warning", relevance: 2 },
  { code: "w056", label: "Tsunami hazard zone", category: "warning", relevance: 3 },
  { code: "w057", label: "Strong currents", category: "warning", relevance: 3 },
  { code: "w058", label: "Boating area", category: "warning", relevance: 3 },
  { code: "w059", label: "Sand yachting", category: "warning", relevance: 3 },
  { code: "w060", label: "Incoming tides", category: "warning", relevance: 3 },
  { code: "w061", label: "Quicksand / deep mud / silt", category: "warning", relevance: 2 },
  { code: "w062", label: "Kite surfing", category: "warning", relevance: 3 },
  { code: "w063", label: "Parasailing", category: "warning", relevance: 3 },
  { code: "w064", label: "Strong winds", category: "warning", relevance: 2 },
  { code: "w065", label: "High surf / large breaking waves", category: "warning", relevance: 3 },
  { code: "w066", label: "Deep shelving beach", category: "warning", relevance: 3 },
  { code: "w067", label: "Crocodiles / alligators / caymans", category: "warning", relevance: 3 },
  { code: "w068", label: "Falling into water from floating surface", category: "warning", relevance: 3 },
  { code: "w069", label: "Jellyfish", category: "warning", relevance: 3 },
  { code: "w070", label: "Step down", category: "warning", relevance: 2 },
  { code: "w071", label: "Substance – health hazard", category: "warning", relevance: 2 },
  { code: "w072", label: "Substance – environmental hazard", category: "warning", relevance: 2 },
  { code: "w073", label: "Large-scale fire zone", category: "warning", relevance: 3 },
  { code: "w074", label: "Tornado zone", category: "warning", relevance: 3 },
  { code: "w075", label: "Active volcano zone", category: "warning", relevance: 3 },
  { code: "w076", label: "Debris flow zone", category: "warning", relevance: 3 },
  { code: "w077", label: "Flood zone", category: "warning", relevance: 3 },
  { code: "w078", label: "Landslide zone", category: "warning", relevance: 3 },

  // ── MANDATORY (M) ──
  { code: "m001", label: "General mandatory action", category: "mandatory", relevance: 1 },
  { code: "m002", label: "Refer to instruction manual", category: "mandatory", relevance: 2 },
  { code: "m003", label: "Wear ear protection", category: "mandatory", relevance: 1 },
  { code: "m004", label: "Wear eye protection", category: "mandatory", relevance: 1 },
  { code: "m005", label: "Connect earth terminal to ground", category: "mandatory", relevance: 3 },
  { code: "m006", label: "Disconnect mains plug", category: "mandatory", relevance: 2 },
  { code: "m007", label: "Opaque eye protection must be worn", category: "mandatory", relevance: 3 },
  { code: "m008", label: "Wear safety footwear", category: "mandatory", relevance: 1 },
  { code: "m009", label: "Wear protective gloves", category: "mandatory", relevance: 1 },
  { code: "m010", label: "Wear protective clothing", category: "mandatory", relevance: 2 },
  { code: "m011", label: "Wash your hands", category: "mandatory", relevance: 1 },
  { code: "m012", label: "Use handrail", category: "mandatory", relevance: 2 },
  { code: "m013", label: "Wear face shield", category: "mandatory", relevance: 1 },
  { code: "m014", label: "Wear head protection", category: "mandatory", relevance: 1 },
  { code: "m015", label: "Wear high-visibility clothing", category: "mandatory", relevance: 1 },
  { code: "m016", label: "Wear a mask", category: "mandatory", relevance: 1 },
  { code: "m017", label: "Wear respiratory protection", category: "mandatory", relevance: 1 },
  { code: "m018", label: "Wear safety harness", category: "mandatory", relevance: 1 },
  { code: "m019", label: "Wear welding mask", category: "mandatory", relevance: 2 },
  { code: "m020", label: "Wear safety belts", category: "mandatory", relevance: 2 },
  { code: "m021", label: "Disconnect before maintenance", category: "mandatory", relevance: 1 },
  { code: "m022", label: "Use barrier cream", category: "mandatory", relevance: 3 },
  { code: "m023", label: "Use footbridge", category: "mandatory", relevance: 2 },
  { code: "m024", label: "Use this walkway", category: "mandatory", relevance: 2 },
  { code: "m025", label: "Protect infants' eyes", category: "mandatory", relevance: 3 },
  { code: "m026", label: "Use protective apron", category: "mandatory", relevance: 2 },
  { code: "m027", label: "Check guard", category: "mandatory", relevance: 2 },
  { code: "m028", label: "Keep locked", category: "mandatory", relevance: 2 },
  { code: "m029", label: "Sound horn", category: "mandatory", relevance: 1 },
  { code: "m030", label: "Use litter bin", category: "mandatory", relevance: 2 },
  { code: "m031", label: "Use table saw adjustable guard", category: "mandatory", relevance: 3 },
  { code: "m032", label: "Wear anti-static footwear", category: "mandatory", relevance: 3 },
  { code: "m033", label: "Close safety bar of chairlift", category: "mandatory", relevance: 3 },
  { code: "m034", label: "Open safety bar of chairlift", category: "mandatory", relevance: 3 },
  { code: "m035", label: "Leave tow-track if falling", category: "mandatory", relevance: 3 },
  { code: "m036", label: "Lift ski tips", category: "mandatory", relevance: 3 },
  { code: "m037", label: "Close and secure hatches – launch", category: "mandatory", relevance: 3 },
  { code: "m038", label: "Start engine – launch", category: "mandatory", relevance: 3 },
  { code: "m039", label: "Lower lifeboat to water – launch", category: "mandatory", relevance: 3 },
  { code: "m040", label: "Lower liferaft to water – launch", category: "mandatory", relevance: 3 },
  { code: "m041", label: "Lower rescue boat – launch", category: "mandatory", relevance: 3 },
  { code: "m042", label: "Release falls – launch", category: "mandatory", relevance: 3 },
  { code: "m043", label: "Start water spray – launch", category: "mandatory", relevance: 3 },
  { code: "m044", label: "Start air supply – launch", category: "mandatory", relevance: 3 },
  { code: "m045", label: "Release lifeboat gripes – launch", category: "mandatory", relevance: 3 },
  { code: "m046", label: "Secure gas cylinders", category: "mandatory", relevance: 2 },
  { code: "m047", label: "Use self-contained breathing apparatus", category: "mandatory", relevance: 2 },
  { code: "m048", label: "Use gas detector", category: "mandatory", relevance: 1 },
  { code: "m049", label: "Wear protective sport equipment", category: "mandatory", relevance: 3 },
  { code: "m050", label: "Alight toboggan to left", category: "mandatory", relevance: 3 },
  { code: "m051", label: "Alight toboggan to right", category: "mandatory", relevance: 3 },
  { code: "m052", label: "Keep distance between toboggans", category: "mandatory", relevance: 3 },
  { code: "m053", label: "Wear personal flotation device", category: "mandatory", relevance: 3 },
  { code: "m054", label: "Supervise children in aquatic environment", category: "mandatory", relevance: 3 },
  { code: "m055", label: "Keep out of reach of children", category: "mandatory", relevance: 3 },
  { code: "m056", label: "Ventilate before and during entering", category: "mandatory", relevance: 1 },
  { code: "m057", label: "Ensure continuous ventilation", category: "mandatory", relevance: 1 },
  { code: "m058", label: "Entry only with supervisor outside", category: "mandatory", relevance: 1 },
  { code: "m059", label: "Wear laboratory coat", category: "mandatory", relevance: 3 },
  { code: "m060", label: "Hold trolley handle", category: "mandatory", relevance: 3 },

  // ── SAFE CONDITION (E) ──
  { code: "e001", label: "Emergency exit (left)", category: "safe", relevance: 1 },
  { code: "e002", label: "Emergency exit (right)", category: "safe", relevance: 1 },
  { code: "e003", label: "First aid", category: "safe", relevance: 1 },
  { code: "e004", label: "Emergency telephone", category: "safe", relevance: 2 },
  { code: "e005", label: "Direction arrow (withdrawn – use 3864)", category: "safe", relevance: 3 },
  { code: "e006", label: "Direction arrow 45° (withdrawn – use 3864)", category: "safe", relevance: 3 },
  { code: "e007", label: "Evacuation assembly point", category: "safe", relevance: 1 },
  { code: "e008", label: "Break to obtain access", category: "safe", relevance: 2 },
  { code: "e009", label: "Doctor", category: "safe", relevance: 2 },
  { code: "e010", label: "Automated external defibrillator (AED)", category: "safe", relevance: 1 },
  { code: "e011", label: "Eyewash station", category: "safe", relevance: 1 },
  { code: "e012", label: "Safety shower", category: "safe", relevance: 1 },
  { code: "e013", label: "Stretcher", category: "safe", relevance: 1 },
  { code: "e014", label: "Child seat detection system (CPOD)", category: "safe", relevance: 3 },
  { code: "e015", label: "Drinking water", category: "safe", relevance: 2 },
  { code: "e016", label: "Emergency window with escape ladder", category: "safe", relevance: 3 },
  { code: "e017", label: "Rescue window", category: "safe", relevance: 3 },
  { code: "e018", label: "Turn anticlockwise to open", category: "safe", relevance: 3 },
  { code: "e019", label: "Turn clockwise to open", category: "safe", relevance: 3 },
  { code: "e020", label: "Emergency stop button", category: "safe", relevance: 2 },
  { code: "e021", label: "Protection shelter", category: "safe", relevance: 2 },
  { code: "e022", label: "Door opens – push left", category: "safe", relevance: 3 },
  { code: "e023", label: "Door opens – push right", category: "safe", relevance: 3 },
  { code: "e024", label: "Evacuation temporary refuge", category: "safe", relevance: 2 },
  { code: "e025", label: "Emergency hammer", category: "safe", relevance: 3 },
  { code: "e026", label: "Emergency exit – mobility impaired (left)", category: "safe", relevance: 2 },
  { code: "e027", label: "Medical grab bag", category: "safe", relevance: 2 },
  { code: "e028", label: "Oxygen resuscitator", category: "safe", relevance: 2 },
  { code: "e029", label: "Emergency escape breathing device", category: "safe", relevance: 2 },
  { code: "e030", label: "Emergency exit – mobility impaired (right)", category: "safe", relevance: 2 },
  { code: "e031", label: "Shipboard general alarm", category: "safe", relevance: 3 },
  { code: "e032", label: "Shipboard assembly station", category: "safe", relevance: 3 },
  { code: "e033", label: "Door slides right to open", category: "safe", relevance: 3 },
  { code: "e034", label: "Door slides left to open", category: "safe", relevance: 3 },
  { code: "e035", label: "Liferaft knife", category: "safe", relevance: 3 },
  { code: "e036", label: "Lifeboat", category: "safe", relevance: 3 },
  { code: "e037", label: "Rescue boat", category: "safe", relevance: 3 },
  { code: "e038", label: "Liferaft", category: "safe", relevance: 3 },
  { code: "e039", label: "Davit-launched liferaft", category: "safe", relevance: 3 },
  { code: "e040", label: "Lifebuoy", category: "safe", relevance: 3 },
  { code: "e041", label: "Lifebuoy with line", category: "safe", relevance: 3 },
  { code: "e042", label: "Lifebuoy with light", category: "safe", relevance: 3 },
  { code: "e043", label: "Lifebuoy with line and light", category: "safe", relevance: 3 },
  { code: "e044", label: "Lifejacket", category: "safe", relevance: 3 },
  { code: "e045", label: "Child's lifejacket", category: "safe", relevance: 3 },
  { code: "e046", label: "Infant's lifejacket", category: "safe", relevance: 3 },
  { code: "e047", label: "Thermal protective aid", category: "safe", relevance: 3 },
  { code: "e048", label: "Survival craft distress signals", category: "safe", relevance: 3 },
  { code: "e049", label: "Rocket parachute flare", category: "safe", relevance: 3 },
  { code: "e050", label: "Line-throwing appliance", category: "safe", relevance: 3 },
  { code: "e051", label: "Two-way VHF radiotelephone", category: "safe", relevance: 3 },
  { code: "e052", label: "Emergency radio beacon (EPIRB)", category: "safe", relevance: 3 },
  { code: "e053", label: "Embarkation ladder", category: "safe", relevance: 3 },
  { code: "e054", label: "Marine evacuation slide", category: "safe", relevance: 3 },
  { code: "e055", label: "Marine evacuation chute", category: "safe", relevance: 3 },
  { code: "e056", label: "Survival clothing", category: "safe", relevance: 3 },
  { code: "e057", label: "Door opens – pull left", category: "safe", relevance: 3 },
  { code: "e058", label: "Door opens – pull right", category: "safe", relevance: 3 },
  { code: "e059", label: "Embarkation ladder", category: "safe", relevance: 3 },
  { code: "e060", label: "Evacuation chair", category: "safe", relevance: 2 },
  { code: "e061", label: "Water life-saving equipment", category: "safe", relevance: 3 },
  { code: "e062", label: "Tsunami evacuation area", category: "safe", relevance: 3 },
  { code: "e063", label: "Tsunami evacuation building", category: "safe", relevance: 3 },
  { code: "e064", label: "First aid responder", category: "safe", relevance: 2 },
  { code: "e065", label: "Natural disaster outdoor refuge area", category: "safe", relevance: 3 },
  { code: "e067", label: "Evacuation mattress", category: "safe", relevance: 3 },
  { code: "e068", label: "Lifebuoy with light and smoke", category: "safe", relevance: 3 },
  { code: "e069", label: "Person overboard call point", category: "safe", relevance: 3 },
  { code: "e070", label: "Evacuation lift – unable to use stairs", category: "safe", relevance: 3 },

  // ── FIRE EQUIPMENT (F) ──
  { code: "f001", label: "Fire extinguisher", category: "fire", relevance: 1 },
  { code: "f002", label: "Fire hose reel", category: "fire", relevance: 1 },
  { code: "f003", label: "Fire ladder", category: "fire", relevance: 2 },
  { code: "f004", label: "Collection of firefighting equipment", category: "fire", relevance: 2 },
  { code: "f005", label: "Fire alarm call point", category: "fire", relevance: 1 },
  { code: "f006", label: "Fire emergency telephone", category: "fire", relevance: 2 },
  { code: "f007", label: "Fire protection door", category: "fire", relevance: 2 },
  { code: "f008", label: "Fixed fire extinguishing battery", category: "fire", relevance: 3 },
  { code: "f009", label: "Wheeled fire extinguisher", category: "fire", relevance: 2 },
  { code: "f010", label: "Portable foam applicator unit", category: "fire", relevance: 3 },
  { code: "f011", label: "Water fog applicator", category: "fire", relevance: 3 },
  { code: "f012", label: "Fixed fire extinguishing installation", category: "fire", relevance: 3 },
  { code: "f013", label: "Fixed fire extinguishing bottle", category: "fire", relevance: 3 },
  { code: "f014", label: "Remote release station", category: "fire", relevance: 3 },
  { code: "f015", label: "Fire monitor", category: "fire", relevance: 3 },
  { code: "f016", label: "Fire blanket", category: "fire", relevance: 1 },
  { code: "f017", label: "Firefighters' lift", category: "fire", relevance: 3 },
  { code: "f018", label: "Fire alarm flashing light", category: "fire", relevance: 2 },
  { code: "f019", label: "Unconnected fire hose", category: "fire", relevance: 3 },
];

/** Paper sizes in mm */
export const PAPER_SIZES = [
  { id: "a4" as const, label: "A4", w: 210, h: 297 },
  { id: "a3" as const, label: "A3", w: 297, h: 420 },
];

export const TEXT_SIZES = [
  { id: "s" as const, label: "S", factor: 0.6 },
  { id: "m" as const, label: "M", factor: 1 },
  { id: "l" as const, label: "L", factor: 1.4 },
  { id: "xl" as const, label: "XL", factor: 1.8 },
];

export const FONTS = [
  { id: "standard" as const, label: "Standard", family: "'Oswald', sans-serif", gf: "Oswald:wght@700" },
  { id: "narrow" as const, label: "Narrow", family: "'Barlow Condensed', sans-serif", gf: "Barlow+Condensed:wght@700" },
  { id: "impact" as const, label: "Impact", family: "'Anton', sans-serif", gf: "Anton" },
];

/** Helper: get icon src path */
export function iconSrc(code: string): string {
  return `/icons/iso7010/${code}.svg`;
}

/** Helper: get category meta for a code */
export function categoryForCode(code: string): CategoryMeta | undefined {
  const prefix = code.charAt(0);
  const catMap: Record<string, SignCategory> = { p: "prohibition", w: "warning", m: "mandatory", e: "safe", f: "fire" };
  return CATEGORIES.find((c) => c.id === catMap[prefix]);
}
