// prisma/seed-content.ts
// Seeds toolbox talk categories, free template categories, and free tool definitions
// Exported as a function — called from seed.ts, not run standalone

import { PrismaClient, TemplateFormat, ToolStatus } from "@prisma/client";

const toolboxCategories = [
  { code: "02.02.01", name: "Working at Height", slug: "working-at-height", description: "Toolbox talks covering ladder safety, scaffold use, edge protection, harness systems, roof work, and fall prevention for construction site teams.", order: 1 },
  { code: "02.02.02", name: "Manual Handling", slug: "manual-handling", description: "Toolbox talks on safe lifting techniques, MAC and RAPP assessments, team handling, reducing musculoskeletal injuries, and mechanical handling aids.", order: 2 },
  { code: "02.02.03", name: "Excavations", slug: "excavations", description: "Toolbox talks covering trench safety, shoring and battering, buried services, edge protection, water ingress, and excavation inspections.", order: 3 },
  { code: "02.02.04", name: "COSHH", slug: "coshh", description: "Toolbox talks on hazardous substances, COSHH assessments, PPE for chemicals, safe storage, exposure limits, and health surveillance.", order: 4 },
  { code: "02.02.05", name: "Electrical Safety", slug: "electrical-safety", description: "Toolbox talks covering overhead and underground cables, temporary electrics, PAT testing, isolation procedures, and 110V tool safety.", order: 5 },
  { code: "02.02.06", name: "Fire Safety", slug: "fire-safety", description: "Toolbox talks on fire prevention, extinguisher use, hot works permits, emergency evacuation, site fire risk, and temporary accommodation fire safety.", order: 6 },
  { code: "02.02.07", name: "Confined Spaces", slug: "confined-spaces", description: "Toolbox talks covering confined space entry procedures, gas monitoring, rescue plans, ventilation, permits to work, and City and Guilds 6160 requirements.", order: 7 },
  { code: "02.02.08", name: "Plant & Vehicles", slug: "plant-and-vehicles", description: "Toolbox talks on plant safety, banksman procedures, vehicle marshalling, pre-use checks, exclusion zones, and site traffic management.", order: 8 },
  { code: "02.02.09", name: "PPE", slug: "ppe", description: "Toolbox talks covering personal protective equipment selection, inspection, maintenance, RPE face-fit testing, and PPE compliance on site.", order: 9 },
  { code: "02.02.10", name: "Slips Trips & Falls", slug: "slips-trips-and-falls", description: "Toolbox talks on housekeeping, walkway management, cable management, wet surfaces, uneven ground, and preventing common site injuries.", order: 10 },
  { code: "02.02.11", name: "Lifting Operations", slug: "lifting-operations", description: "Toolbox talks covering lift planning, LOLER requirements, sling inspections, exclusion zones, appointed persons, and lifting equipment checks.", order: 11 },
  { code: "02.02.12", name: "Noise & Vibration", slug: "noise-and-vibration", description: "Toolbox talks on HAVS prevention, noise exposure limits, hearing protection, vibration-reducing tools, health surveillance, and trigger time management.", order: 12 },
  { code: "02.02.13", name: "Dust & Silica", slug: "dust-and-silica", description: "Toolbox talks covering silica dust risks, RPE selection, dust suppression methods, exposure monitoring, LEV systems, and health surveillance.", order: 13 },
  { code: "02.02.14", name: "Environmental", slug: "environmental", description: "Toolbox talks on pollution prevention, spill response, waste management, protected species, water course protection, and environmental permits.", order: 14 },
  { code: "02.02.15", name: "Welfare & Wellbeing", slug: "welfare-and-wellbeing", description: "Toolbox talks covering mental health awareness, fatigue management, hydration, welfare facilities, work-life balance, and site wellbeing initiatives.", order: 15 },
  { code: "02.02.17", name: "Traffic Management", slug: "traffic-management", description: "Toolbox talks on site traffic plans, pedestrian segregation, speed limits, signage, Chapter 8 requirements, and reversing vehicle procedures.", order: 16 },
  { code: "02.02.18", name: "Housekeeping", slug: "housekeeping", description: "Toolbox talks covering workplace tidiness, waste segregation, material storage, access route maintenance, and 5S principles on construction sites.", order: 17 },
  { code: "02.02.19", name: "Behavioural Safety", slug: "behavioural-safety", description: "Toolbox talks on safety culture, near-miss reporting, behavioural observations, complacency, positive interventions, and personal accountability.", order: 18 },
  { code: "02.02.20", name: "Seasonal Hazards", slug: "seasonal-hazards", description: "Toolbox talks covering winter working, ice and frost, sun exposure, heat stress, wind hazards, flooding risks, and seasonal weather preparations.", order: 19 },
  { code: "02.02.21", name: "General & Other", slug: "general-and-other", description: "General toolbox talks covering miscellaneous safety topics, site rules, induction refreshers, safety stand-downs, and cross-cutting awareness items.", order: 20 },
  { code: "02.02.22", name: "Power & Hand Tools", slug: "power-and-hand-tools", description: "Toolbox talks on angle grinder safety, disc cutter use, drill safety, hand tool inspections, guards, and correct tool selection for the task.", order: 21 },
  { code: "02.02.23", name: "Water & Flooding", slug: "water-and-flooding", description: "Toolbox talks covering working near water, flood risk, dewatering, temporary dams, drowning prevention, and wet weather contingency plans.", order: 22 },
  { code: "02.02.24", name: "Cranes & Lifting", slug: "cranes-and-lifting", description: "Toolbox talks on crane operations, outrigger setup, load charts, wind speed limits, lifting accessories, and crane exclusion zones.", order: 23 },
  { code: "02.02.25", name: "First Aid & Emergency", slug: "first-aid-and-emergency", description: "Toolbox talks covering first aid provision, emergency procedures, AED use, incident reporting, muster points, and emergency contact arrangements.", order: 24 },
  { code: "02.02.26", name: "Asbestos", slug: "asbestos", description: "Toolbox talks on asbestos awareness, refurbishment and demolition surveys, licensed and non-licensed work, duty to manage, and emergency procedures.", order: 25 },
  { code: "02.02.27", name: "Site Security & Access", slug: "site-security-and-access", description: "Toolbox talks covering site security, access control, visitor management, theft prevention, perimeter fencing, and out-of-hours arrangements.", order: 26 },
  { code: "02.02.28", name: "Welfare & Hygiene", slug: "welfare-and-hygiene", description: "Toolbox talks on hand hygiene, welfare facility standards, dermatitis prevention, food hygiene, Weil's disease awareness, and occupational health basics.", order: 27 },
];

const templateCategories = [
  { name: "Project Management", slug: "project-management", format: TemplateFormat.EXCEL, description: "Free Excel project management templates including trackers, logs, registers, and scheduling tools for construction projects.", order: 1 },
  { name: "Health & Safety", slug: "health-and-safety", format: TemplateFormat.EXCEL, description: "Free Excel health and safety templates including risk assessments, inspection checklists, COSHH registers, and permit trackers.", order: 2 },
  { name: "Quality Management", slug: "quality-management", format: TemplateFormat.EXCEL, description: "Free Excel quality management templates including ITPs, NCR logs, snag lists, and inspection registers for construction.", order: 3 },
  { name: "Environmental", slug: "environmental", format: TemplateFormat.EXCEL, description: "Free Excel environmental templates including waste transfer logs, carbon trackers, spill response records, and environmental checklists.", order: 4 },
  { name: "Programme & Planning", slug: "programme-and-planning", format: TemplateFormat.EXCEL, description: "Free Excel planning templates including Gantt charts, lookahead programmes, milestone trackers, and resource allocation sheets.", order: 5 },
  { name: "Commercial & QS", slug: "commercial-and-qs", format: TemplateFormat.EXCEL, description: "Free Excel commercial templates including valuation trackers, cost schedules, variation registers, and interim payment calculators.", order: 6 },
  { name: "Site Management", slug: "site-management", format: TemplateFormat.EXCEL, description: "Free Excel site management templates including daily reports, allocation sheets, attendance logs, and delivery booking systems.", order: 7 },
  { name: "Plant & Equipment", slug: "plant-and-equipment", format: TemplateFormat.EXCEL, description: "Free Excel plant templates including pre-use check sheets, maintenance logs, plant registers, and equipment allocation trackers.", order: 8 },
  { name: "Training & Competence", slug: "training-and-competence", format: TemplateFormat.EXCEL, description: "Free Excel training templates including competence matrices, induction records, training needs analyses, and certification trackers.", order: 9 },
  { name: "Temporary Works", slug: "temporary-works", format: TemplateFormat.WORD, description: "Free Word temporary works templates including TWC registers, design check requests, briefing records, and inspection checklists.", order: 10 },
  { name: "Subcontractor Management", slug: "subcontractor-management", format: TemplateFormat.WORD, description: "Free Word subcontractor templates including performance scorecards, pre-start meeting agendas, payment certification forms, and compliance checklists.", order: 11 },
  { name: "Document Control", slug: "document-control", format: TemplateFormat.WORD, description: "Free Word document control templates including transmittal forms, drawing registers, document review logs, and revision tracking sheets.", order: 12 },
  { name: "Meeting & Communication", slug: "meeting-and-communication", format: TemplateFormat.WORD, description: "Free Word meeting templates including minutes formats, briefing pack structures, progress meeting agendas, and action tracking sheets.", order: 13 },
  { name: "Reporting", slug: "reporting", format: TemplateFormat.POWERPOINT, description: "Free PowerPoint reporting templates including weekly and monthly progress reports, KPI dashboards, and management summary presentations.", order: 14 },
  { name: "Handover & Completion", slug: "handover-and-completion", format: TemplateFormat.POWERPOINT, description: "Free PowerPoint handover templates including O&M submission checklists, practical completion packs, snagging presentations, and close-out reports.", order: 15 },
];

const freeTools = [
  { name: "Manual Handling Risk Score Calculator", slug: "manual-handling-calculator", description: "Score manual handling tasks using HSE MAC (lift, carry, team handling) and RAPP (push and pull) methodologies. 120+ civil engineering task library with search, HSE colour-coded risk scoring, suggested controls, before/after re-score workflow, and professional PDF assessment output.", features: "Combined MAC + RAPP scoring,120+ task library with search,HSE colour-coded output,Suggested controls,Re-score workflow,Professional PDF export", status: ToolStatus.LIVE, route: "/tools/manual-handling-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/manual-handling-risk-score-calculator", order: 1 },
  { name: "Fire Risk Score Calculator", slug: "fire-risk-score-calculator", description: "Score fire risk on construction sites using PAS 79 methodology and the Fire Safety Order 2005. Three site types (offices, live construction, occupied building), 5×5 likelihood × consequence risk matrix, section-by-section scoring with regulatory references, auto-generated prioritised action plan, and professional PDF export.", features: "PAS 79 methodology,3 site types,5×5 risk matrix,FSO 2005 regulatory refs,Action plan generator,Editable actions,Professional PDF export", status: ToolStatus.LIVE, route: "/tools/fire-risk-score-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/fire-risk-score-calculator", order: 2 },
  { name: "Civil Engineering Materials Converter", slug: "materials-converter", description: "Convert between tonnes, cubic metres, kilograms, litres, square metres, bulk bags, and wagon loads for 100+ civil engineering materials. Includes loose and compacted densities, cost estimating, and embodied carbon calculations using ICE v3 emission factors.", features: "100+ materials,7 unit types,Loose vs compacted density,Cost estimating with editable rates,ICE v3/v4 carbon factors,Live category subtotals,Multi-row take-off with CSV export,Editable assumptions", status: ToolStatus.LIVE, route: "/tools/materials-converter", gumroadUrl: "https://ebrora.gumroad.com/l/civil-engineering-materials-converter", order: 3 },
  { name: "HAV Exposure Calculator", slug: "hav-calculator", description: "Calculate hand-arm vibration exposure using the HSE points method per the Control of Vibration at Work Regulations 2005. 151-tool library with multi-operative daily and weekly logging, EAV/ELV traffic light scoring, magnitude override, and per-operative PDF assessment.", features: "151-tool library,HSE points method,Multi-operative,Daily/weekly modes,EAV/ELV traffic light,Magnitude override,Custom tools,Operative dashboard,Per-operative PDF,White-label PDF", status: ToolStatus.LIVE, route: "/tools/hav-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/hav-calculator", order: 6 },
  { name: "Confined Space Category Calculator", slug: "confined-space-calculator", description: "Calculate the confined space risk category (NC1 Low Risk through to NC4 High Risk with Rescue) using a weighted scoring system covering specified risks, depth, access, ventilation, atmosphere, and communication. Full requirements checklist with C&G 6160 qualification mapping.", features: "NC1 to NC4 categories,Weighted scoring,Gate questions,Full requirements checklist,C&G 6160 mapping,Score breakdown,Interactive checklist,White-label PDF", status: ToolStatus.LIVE, route: "/tools/confined-space-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/confined-space-calculator", order: 7 },
  { name: "Access Equipment Selector", slug: "access-equipment-selector", description: "HSE hierarchy-compliant decision-support tool for selecting the safest reasonably practicable access equipment. Enter your site conditions and get ranked recommendations across 14 equipment types — with full justification, training requirements, rescue plan notes, and a print-ready PDF assessment.", features: "HSE Hierarchy Compliant,14 Equipment Types,Automated Ranking,Scoring Transparency,PDF Export,Diesel MEWP Auto-Select", status: ToolStatus.LIVE, route: "/tools/access-equipment-selector", gumroadUrl: "https://ebrora.gumroad.com/l/access-equipment-selector", order: 5 },
  { name: "Fuel Usage Calculator", slug: "fuel-usage-calculator", description: "Plan fuel usage, cost, and carbon emissions for construction site plant. 370+ machines from Caterpillar, Komatsu, Hitachi, Volvo, JCB, and more — plus generic fallbacks by type and size. Multi-machine planning with daily and weekly breakdowns, editable fuel cost, HVO carbon factor, and professional landscape PDF export.", features: "370+ machines,Multi-machine planning,Daily/weekly dashboard,Cost calculation,CO₂e carbon reporting,Generic fallbacks,HVO support,Professional PDF export", status: ToolStatus.LIVE, route: "/tools/fuel-usage-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/fuel-usage-calculator", order: 8 },
  { name: "WBGT Heat Stress Calculator", slug: "wbgt-heat-stress-calculator", description: "Assess heat stress risk using ISO 7243 Wet Bulb Globe Temperature. Enter conditions directly or estimate from basic weather data. Work/rest ratios, daily and weekly planners, 19-control action plan database, and professional PDF assessment with sign-off.", features: "ISO 7243 compliant,Direct & estimated modes,Work/rest ratios,Daily & weekly planner,19-control database,Met Office link,Professional PDF export", status: ToolStatus.LIVE, route: "/tools/wbgt-heat-stress-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/wbgt-heat-stress-calculator", order: 9 },
  { name: "Plant Pre-Use Check Sheet Creator", slug: "plant-pre-use-checksheet", description: "Generate PUWER-compliant daily pre-use inspection check sheets for 28 plant types. Weekly Mon–Sun grid with ✓/✗/N/A marking, fleet mode for multiple machines, blank PDF download for site printing, custom check items, and CPCS/NPORS card expiry tracking.", features: "28 plant types,25 checks per type,Mon–Sun weekly grid,Fleet mode,Blank PDF download,Custom check items,CPCS expiry tracking,Professional PDF export", status: ToolStatus.LIVE, route: "/tools/plant-pre-use-checksheet", gumroadUrl: "https://ebrora.gumroad.com/l/plant-pre-use-checksheet", order: 10 },
  { name: "Construction Productivity Calculator", slug: "construction-productivity-calculator", description: "Estimate daily outputs for 9 UK civil engineering task types: steel fixing, pipe laying, muck shift, formwork, concreting, kerb laying, piling, road base laying, and asphalt. Full calculation chain with region, constraint, crew, and task-specific factors. Based on Spon's, CIRIA and industry norms.", features: "9 task types,Full factor chain,Days-to-complete,Combined summary,Spon's/CIRIA based,All rates overridable,Professional PDF export", status: ToolStatus.LIVE, route: "/tools/construction-productivity-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/construction-productivity-calculator", order: 11 },
  { name: "Concrete Volume Calculator", slug: "concrete-volume-calculator", description: "Calculate concrete volumes for 9 shape types including slabs, columns, beams, ring beams, pile caps, and stairs. Multi-element take-off with configurable waste factor, truck load calculation, UK concrete mix database (C8/10 to C40/50), and white-label PDF.", features: "9 shape types,Multi-element,Waste factor,Truck loads,UK mix database,Manual override,White-label PDF", status: ToolStatus.LIVE, route: "/tools/concrete-volume-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/concrete-volume-calculator", order: 12 },
  { name: "Aggregate & MOT Type 1 Calculator", slug: "aggregate-calculator", description: "Calculate tonnage, compacted and loose volumes, wagon loads, and bulk bag counts for 26 UK aggregate materials including MOT Type 1 & 2, 6F2, 6F5, GSB, sands, gravels, recycled aggregates, and specialist materials.", features: "26 materials,6 categories,Compacted & loose volumes,Wagon loads,Bulk bags,Editable densities,White-label PDF", status: ToolStatus.LIVE, route: "/tools/aggregate-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/aggregate-calculator", order: 13 },
  { name: "Excavation & Spoil Calculator", slug: "excavation-spoil-calculator", description: "Calculate bank and bulked volumes, tonnage and wagon loads for 8 soil types. Multi-area take-off with manual override on densities and bulking factors. White-label PDF export.", features: "8 soil types,Bank & bulked volumes,Tonnage,Wagon loads,Editable densities,Manual bulking override,White-label PDF", status: ToolStatus.LIVE, route: "/tools/excavation-spoil-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/excavation-spoil-calculator", order: 14 },
  { name: "Trench Backfill & Pipe Bedding Calculator", slug: "trench-backfill-calculator", description: "Calculate bedding, side fill, and backfill volumes per HAUC/SROH specification. Material selectors per zone, excavated material re-use toggle, net import/export tonnage, and white-label PDF.", features: "HAUC/SROH zones,8 backfill materials,Per-zone material selection,Re-use toggle,Import/export tonnage,Overridable depths,White-label PDF", status: ToolStatus.LIVE, route: "/tools/trench-backfill-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/trench-backfill-calculator", order: 15 },
  { name: "Brick & Block Quantity Calculator", slug: "brick-block-calculator", description: "Calculate brick and block quantities for 17 UK masonry unit types. Opening deductions for doors and windows, 4 mortar mix designations (M2–M12), cement bags and sand tonnage, multi-wall section take-off.", features: "17 masonry units,4 mortar types,Opening deductions,Cement & sand calc,Multi-wall,Override rates,White-label PDF", status: ToolStatus.LIVE, route: "/tools/brick-block-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/brick-block-calculator", order: 16 },
  { name: "Concrete Pour Planner", slug: "concrete-pour-planner", description: "Plan ready-mix concrete pours with truck dispatch schedules. Calculate trucks required, concurrent trucks on-site, pour duration, first/last arrival times, and visual progress tracking. UK concrete mix database.", features: "Truck dispatch schedule,Concurrent truck calc,Pour duration,Progress tracking,UK mix database,Override all inputs,White-label PDF", status: ToolStatus.LIVE, route: "/tools/concrete-pour-planner", gumroadUrl: "https://ebrora.gumroad.com/l/concrete-pour-planner", order: 17 },
  { name: "Welfare Facilities Calculator (CDM 2015)", slug: "welfare-facilities-calculator", description: "Calculate minimum welfare facility requirements for construction sites per CDM 2015 Schedule 2, HSG150, and BS 6465. Male/female separate provision, toilet/wash/rest/drying/first aid calculations, welfare unit hire recommendations, compliance traffic light, and white-label PDF.", features: "CDM 2015 Schedule 2,HSG150 / BS 6465,Male/female ratios,Unit hire configs,Compliance traffic light,CDM checklist,Sign-off section,White-label PDF", status: ToolStatus.LIVE, route: "/tools/welfare-facilities-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/welfare-facilities-calculator", order: 18 },
  { name: "Dust & Silica Exposure Calculator (COSHH)", slug: "dust-silica-calculator", description: "Calculate respirable crystalline silica (RCS) and dust 8-hour TWA exposure for construction activities per COSHH 2002, EH40/2005, and HSE INDG463. 28-activity database with manual entry, COSHH control hierarchy with cost/practicality ranking, RPE recommendations, and white-label PDF.", features: "COSHH 2002 / EH40,28 activity database,Manual entry,8hr TWA calculation,Control hierarchy,RPE recommendation,Time to WEL,White-label PDF", status: ToolStatus.LIVE, route: "/tools/dust-silica-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/dust-silica-calculator", order: 19 },
  { name: "Noise Exposure Calculator (LEP,d)", slug: "noise-exposure-calculator", description: "Calculate daily personal noise exposure LEP,d for construction activities per the Control of Noise at Work Regulations 2005, HSE L108, and ISO 9612. 90+ activity database with manual entry, HPE attenuation using the SNR method with real-world derating, exposure action value checks, and white-label PDF.", features: "Noise at Work Regs 2005,HSE L108 / ISO 9612,90+ activity database,Manual entry,LEP d calculation,HPE SNR attenuation,Action value checks,White-label PDF", status: ToolStatus.LIVE, route: "/tools/noise-exposure-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/noise-exposure-calculator", order: 20 },
  { name: "Slip Risk Assessment Calculator", slug: "slip-risk-calculator", description: "Score slip risk for floor surfaces, walkways, and access routes using the HSE slip assessment methodology (GEIS2). 80+ surface types, multi-zone assessment, contamination and human factor scoring, control measure recommendations, and white-label PDF.", features: "HSE GEIS2 methodology,80+ surface types,Multi-zone assessment,Contamination scoring,Human factors,Control measures,Sign-off section,White-label PDF", status: ToolStatus.LIVE, route: "/tools/slip-risk-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/slip-risk-calculator", order: 21 },
  { name: "CBR to Stiffness Modulus Converter", slug: "cbr-modulus-converter", description: "Convert California Bearing Ratio (CBR) to subgrade stiffness modulus and vice versa using Powell (TRL/DMRB), AASHTO, and South African methods. DMRB HD 26 subgrade classification, 23 common soil type reference table, interactive chart, and PDF export.", features: "Powell / AASHTO / SA methods,Bidirectional conversion,DMRB HD 26 classes,23 soil types,Interactive chart,Design guidance,Sign-off section,PDF export", status: ToolStatus.LIVE, route: "/tools/cbr-modulus-converter", gumroadUrl: "https://ebrora.gumroad.com/l/cbr-modulus-converter", order: 22 },
  { name: "Topsoil Volume & Tonnage Calculator", slug: "topsoil-calculator", description: "Calculate topsoil volumes, tonnage, wagon loads, and costs for landscaping and reinstatement. BS 3882:2015 grade specifications, multi-area take-off, settlement factor, depth guidance, and PDF export.", features: "BS 3882:2015 grades,Multi-area take-off,Settlement factor,Depth guidance,Wagon/bag loads,Cost estimate,Sign-off section,PDF export", status: ToolStatus.LIVE, route: "/tools/topsoil-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/topsoil-calculator", order: 23 },
  { name: "Drainage / Pipe Flow Calculator", slug: "drainage-pipe-flow-calculator", description: "Calculate pipe flow capacity, velocity, and proportional depth for gravity drainage using Colebrook-White and Manning equations. 12 pipe materials, interactive cross-section, Building Regs Part H design checks, and white-label PDF.", features: "Colebrook-White / Manning,12 pipe materials,Proportional depth flow,Pipe cross-section,Building Regs Part H,Design checks,Sign-off section,White-label PDF", status: ToolStatus.LIVE, route: "/tools/drainage-pipe-flow-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/drainage-pipe-flow-calculator", order: 24 },
  { name: "UV Index Exposure Checker", slug: "uv-index-exposure-checker", description: "Calculate UV index exposure for outdoor construction workers using solar position equations and WHO/WMO data. 35 UK cities, hourly UV chart, cumulative SED tracking against HSE 2 SED/day threshold, Fitzpatrick skin type burn time estimates, PPE protection comparison, and professional PDF export.", features: "Solar position engine,35 UK cities,Hourly UV chart,Cumulative SED tracking,HSE 2 SED threshold,Fitzpatrick skin types,PPE comparison,Shade break schedule,Professional PDF export", status: ToolStatus.LIVE, route: "/tools/uv-index-exposure-checker", gumroadUrl: "https://ebrora.gumroad.com/l/uv-index-exposure-checker", order: 25 },
  { name: "Cold Stress Wind Chill Calculator", slug: "cold-stress-wind-chill-calculator", description: "Calculate wind chill temperature using the North American Wind Chill Index formula (Environment Canada / US NWS). Frostbite time thresholds, hypothermia risk assessment with work/warm-up schedules, CSA Z1004-12 clothing requirements, interactive heatmap matrix, and professional PDF export.", features: "North American WCI formula,Frostbite time thresholds,Hypothermia risk assessment,Work/warm-up schedules,CSA Z1004-12 clothing,Heatmap matrix,Wind curve chart,Frostbite gauge,Professional PDF export", status: ToolStatus.LIVE, route: "/tools/cold-stress-wind-chill-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/cold-stress-wind-chill-calculator", order: 26 },
  { name: "Lone Worker Risk Score Calculator", slug: "lone-worker-risk-calculator", description: "Score lone worker risk using HSE INDG73 methodology with multiplicative risk model. 8 weighted risk factors, radar chart, risk gauge, what-if comparison, BS 8484 device recommendations, pre-start checklist, and white-label PDF export.", features: "HSE INDG73 methodology,Multiplicative scoring,8 weighted factors,Radar spider chart,Risk gauge,What-if comparison,BS 8484 references,Pre-start checklist,White-label PDF", status: ToolStatus.LIVE, route: "/tools/lone-worker-risk-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/lone-worker-risk-calculator", order: 27 },
  { name: "Fatigue Risk Calculator (Shift Patterns)", slug: "fatigue-risk-calculator", description: "Assess shift pattern fatigue risk using the HSE RR446 model. Weekly or rotation patterns up to 28 days, fatigue index chart, cumulative sleep debt tracking, relative risk multipliers, Working Time Regulations compliance, preset patterns, and professional landscape PDF export.", features: "HSE RR446 model,Weekly + rotation modes,Up to 28 days,Preset patterns,Fatigue index chart,Sleep debt tracking,Risk multipliers,WTR compliance check,Landscape PDF export", status: ToolStatus.LIVE, route: "/tools/fatigue-risk-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/fatigue-risk-calculator", order: 28 },
  { name: "First Aid Needs Assessment Calculator", slug: "first-aid-needs-calculator", description: "Calculate minimum first aid requirements per HSE L74 and the First-Aid Regulations 1981. FAW/EFAW ratios by risk level, shift coverage matrix, BS 8599-1:2019 kit checklist, AED recommendations, supplementary equipment for specific hazards, optional current provision comparison, and professional PDF export.", features: "HSE L74 methodology,FAW/EFAW ratios,Multi-shift coverage,BS 8599-1 kit checklist,AED recommendations,8 specific hazards,Current provision comparison,Supplementary equipment,Professional PDF export", status: ToolStatus.LIVE, route: "/tools/first-aid-needs-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/first-aid-needs-calculator", order: 29 },
  { name: "Scaffold Load Calculator", slug: "scaffold-load-calculator", description: "Calculate scaffold standard loads per BS EN 12811-1, BS 5975, and SG4:10. Dead, imposed, and wind load breakdown, utilisation gauge, duty class comparison, tie load calculation, sheeted vs unsheeted wind comparison, and white-label PDF export.", features: "BS EN 12811-1 loading,BS 5975 capacity,SG4:10 guidance,Stacked load chart,Utilisation gauge,6 duty classes,Tie load calculation,Sheeted comparison,White-label PDF", status: ToolStatus.LIVE, route: "/tools/scaffold-load-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/scaffold-load-calculator", order: 30 },
  { name: "Formwork Lateral Pressure Calculator", slug: "formwork-pressure-calculator", description: "Calculate formwork lateral pressure using CIRIA Report 108 with DIN 18218 comparison. Pressure vs depth profile, pour rate and temperature sensitivity, form tie spacing back-calculation, and white-label PDF export.", features: "CIRIA Report 108,DIN 18218 comparison,Pressure profile chart,Pour rate sensitivity,Temperature sensitivity,Tie spacing calc,4 concrete types,3 formwork finishes,White-label PDF", status: ToolStatus.LIVE, route: "/tools/formwork-pressure-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/formwork-pressure-calculator", order: 31 },
  { name: "Sling / Lifting Gear SWL Calculator", slug: "sling-swl-calculator", description: "Calculate the effective Safe Working Load (SWL) of multi-leg sling sets per LEEA guidance. Chain, wire rope, and textile slings. Mode factors, angle reduction, capacity curve chart, utilisation gauge, risk banding, and professional PDF export.", features: "LEEA angle factors,4 sling types,1-4 leg configs,Direct & geometry angle input,Capacity curve chart,Utilisation gauge,Risk banding,Max safe angle/load,Sign-off section,Professional PDF export", status: ToolStatus.LIVE, route: "/tools/sling-swl-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/sling-swl-calculator", order: 32 },
  { name: "Soil Compaction Calculator", slug: "soil-compaction-calculator", description: "Calculate compaction layer thickness, minimum passes, and estimated time per SHW Series 600 Table 6/1. 8 material types, 11 equipment categories, multi-zone assessment, automatic equipment comparison, end-product testing requirements, and white-label PDF export.", features: "SHW Table 6/1,8 material types,11 equipment categories,Multi-zone,Area & time estimates,Auto equipment comparison,End-product % MDD,Testing requirements,Layer diagram,White-label PDF", status: ToolStatus.LIVE, route: "/tools/soil-compaction-calculator", gumroadUrl: "https://ebrora.gumroad.com/l/soil-compaction-calculator", order: 33 },
  { name: "Sunrise & Sunset Times", slug: "sunrise-sunset-times", description: "Calculate sunrise, sunset, civil twilight, and recommended construction working hours for 12 major UK cities. Day, week, and month views. NOAA Solar Position Algorithm. CDM 2015 Reg 34 compliant.", features: "12 UK cities,NOAA algorithm,Civil twilight,Day/week/month views,Recommended work hours,BST/GMT auto,Sky arc graphic,CDM 2015 Reg 34,Professional PDF", status: ToolStatus.LIVE, route: "/tools/sunrise-sunset-times", gumroadUrl: "", order: 34 },
  { name: "Plate Bearing Test Interpreter", slug: "plate-bearing-test-interpreter", description: "Interpret plate bearing test results per DIN 18134. Calculate Ev1 and Ev2 deformation modulus, Ev2/Ev1 compaction quality ratio, pass/fail against 20 target presets, CBR equivalent, load-settlement curves, multi-test comparison, and professional PDF export.", features: "DIN 18134,Ev1 & Ev2 modulus,Ev2/Ev1 ratio,20 target presets,CBR correlation,Load-settlement chart,Multi-test comparison,Pass/fail assessment,Stress range override,Professional PDF", status: ToolStatus.LIVE, route: "/tools/plate-bearing-test-interpreter", gumroadUrl: "", order: 35 },
  { name: "Cable Trench Depth & Separation Checker", slug: "cable-trench-depth-checker", description: "Check minimum cover depths and horizontal separation distances for underground utilities in shared trenches. 10 service types, 9 surface types, NJUG Vol 1, NRSWA 1991, ENA TS 09-1/09-2, IGEM/TD/3, Water UK, BT/Openreach specs. Interactive cross-section diagram, compliance checklist, and white-label PDF export.", features: "10 service types,9 surface types,NJUG Vol 1,NRSWA 1991,ENA TS 09,IGEM/TD/3,Water UK,BT specs,Cross-section diagram,Cover depth check,Separation check,Compliance checklist,Width constraint,Crossing detection,Colour legend,White-label PDF", status: ToolStatus.LIVE, route: "/tools/cable-trench-depth-checker", gumroadUrl: "", order: 36 },
  { name: "Concrete Curing Time Estimator", slug: "concrete-curing-estimator", description: "Estimate concrete curing time using the Nurse-Saul maturity method per BS EN 1992-1-1 (Eurocode 2) and PD 6687. 12 strength classes, 7 cement types, 5 curing methods, element thickness insulation boost, strength development curves, milestone tracking, temperature sensitivity analysis, and white-label PDF export.", features: "Nurse-Saul maturity,BS EN 1992-1-1,12 strength classes,7 cement types,5 curing methods,Element thickness,Insulation boost,Strength curves,Milestone tracking,Temperature sensitivity,Cold/frost/hot warnings,White-label PDF", status: ToolStatus.LIVE, route: "/tools/concrete-curing-estimator", gumroadUrl: "", order: 37 },
  { name: "Working Days Calculator", slug: "working-days-calculator", description: "Calculate net working days between two dates, excluding weekends, UK bank holidays (England & Wales, Scotland, Northern Ireland 2025-2035), and custom shutdown periods. Compact Gantt calendar, monthly breakdown chart, programme weeks, and white-label PDF export for NEC4 programme planning.", features: "UK bank holidays 2025-2035,England & Wales,Scotland,Northern Ireland,Easter computus,Weekend exclusion rules,Custom shutdown periods,Gantt calendar,Monthly breakdown,Programme weeks,Working days %,White-label PDF", status: ToolStatus.LIVE, route: "/tools/working-days-calculator", gumroadUrl: "", order: 38 },
  { name: "Daywork Rate Calculator", slug: "daywork-rate-calculator", description: "Calculate daywork valuations per RICS Definition of Prime Cost of Daywork (Civil Engineering & Building editions). Multi-line labour with 12 trade grades (CIJC 2025/26 rates), plant, and materials sections. Percentage additions, optional measured rate comparison, cost breakdown charts, and white-label PDF daywork sheet.", features: "RICS Daywork,Civil Engineering edition,Building edition,12 labour grades,CIJC 2025/26 rates,Multi-line labour,Multi-line plant,Multi-line materials,Percentage additions,Measured rate comparison,Cost breakdown chart,Pie chart,White-label PDF", status: ToolStatus.LIVE, route: "/tools/daywork-rate-calculator", gumroadUrl: "", order: 39 },
  { name: "Plant Hire Cost Comparator", slug: "plant-hire-comparator", description: "Compare total cost of hiring vs buying construction plant using RICS Schedule of Basic Plant Charges methodology. Cumulative cost crossover chart, breakeven analysis, ownership cost breakdown (depreciation, finance, maintenance, insurance, mob/demob), duration sensitivity, effective hourly rates, multi-item support, and white-label PDF export.", features: "RICS methodology,Hire vs buy analysis,Cumulative cost chart,Breakeven calculation,Ownership breakdown,Duration sensitivity,Effective hourly rates,Multi-item comparison,Project-only depreciation,Amortisation option,Mob/demob costs,White-label PDF", status: ToolStatus.LIVE, route: "/tools/plant-hire-comparator", gumroadUrl: "", order: 40 },
  { name: "Overtime Cost Calculator", slug: "overtime-cost-calculator", description: "Calculate overtime costs, premiums, and effective hourly rates for construction teams. Multi-group support, CIJC/NAECI presets, employer on-costs (NIC, pension, CITB levy), hire-vs-overtime breakeven analysis, stacked bar/line/pie charts, Working Time Regulations 1998, and professional PDF export.", features: "Multi-group,CIJC presets,NAECI presets,5 OT tiers,Employer NIC,Pension,CITB levy,Effective rate,Hire vs OT,Stacked bar chart,Cumulative line chart,Pie chart,WTR 1998 warning,Annual projection,Professional PDF", status: ToolStatus.LIVE, route: "/tools/overtime-cost-calculator", gumroadUrl: "", order: 41 },
  { name: "Ecological Exclusion Zone Checker", slug: "ecological-exclusion-zone-checker", description: "Check ecological constraints for UK construction projects. 40+ protected species including all UK bat species, GCN, nesting birds, badgers, otters, water voles, reptiles, dormice, red squirrels, crayfish, salmon, lamprey, invasive plants, TPO trees. 4-level traffic light compliance, 12-month Gantt calendar, exclusion zones, optimal works window finder, and landscape PDF. WCA 1981, Habitats Regs 2017, Badgers Act 1992, NERC 2006.", features: "40+ species,17 bat species,GCN,Nesting birds,Badgers,Otters,Water voles,6 reptiles,Dormice,Red squirrels,Crayfish,Salmon,Lamprey,Invasive plants,TPO trees,13 works types,4-level traffic light,12-month Gantt,Optimal window finder,Exclusion zones,EPS licensing,Survey requirements,WCA 1981,Habitats Regs 2017,Landscape PDF", status: ToolStatus.LIVE, route: "/tools/ecological-exclusion-zone-checker", gumroadUrl: "", order: 42 },
];

export async function seedContent(prisma: PrismaClient) {
  console.log("Seeding content data...");

  console.log("  Seeding 27 toolbox talk categories...");
  for (const cat of toolboxCategories) {
    await prisma.toolboxCategory.upsert({
      where: { code: cat.code },
      update: { name: cat.name, slug: cat.slug, description: cat.description, order: cat.order },
      create: cat,
    });
  }

  console.log("  Seeding 15 free template categories...");
  for (const cat of templateCategories) {
    await prisma.freeTemplateCategory.upsert({
      where: { format_slug: { format: cat.format, slug: cat.slug } },
      update: { name: cat.name, description: cat.description, order: cat.order },
      create: cat,
    });
  }

  console.log("  Seeding 6 free tool definitions...");
  for (const tool of freeTools) {
    await prisma.freeTool.upsert({
      where: { slug: tool.slug },
      update: { name: tool.name, description: tool.description, features: tool.features, status: tool.status, route: tool.route, gumroadUrl: tool.gumroadUrl, order: tool.order },
      create: tool,
    });
  }

  console.log("  Content seed complete (27 categories + 15 templates + 5 tools).");
}
